// Brooks Order Guide (Sep 2026) — the standing product catalog for Between the
// Buns, decoded from the supplier order guide PDF. Grouped by the guide's own
// categories/suppliers. Static reference data: the order sheet renders these as
// editable PAR/on-hand rows and computes ORDER = PAR − On hand (see the
// order-sheet page). `n` is the supplier item number (blank where the guide
// lists none). Regenerate from the source PDF if the guide changes.

export interface OrderGuideItem {
  /** Supplier item number, if the guide lists one. */
  n: string;
  /** Item description as printed in the guide. */
  name: string;
}

export interface OrderGuideCategory {
  category: string;
  items: OrderGuideItem[];
}

export const BROOKS_ORDER_GUIDE: readonly OrderGuideCategory[] = [
  {
    category: "Take Out Supply",
    items: [
      { n: "1360227", name: "Containers, 4oz Kraft Paper" },
      { n: "1418243", name: "Containers, 35oz White Bagasse Paper Hinged, 9 X 6 X 3In, Compostable" },
      { n: "1418239", name: "Containers, 23oz White Bagasse Paper Hinged, 6 X 6 X 3In, Compostable" },
      { n: "1377600", name: "Straws, 8In White Paper Milkshake, Wrapped" },
      { n: "1172797", name: "Cups, 2oz Translucent Plastic Portion" },
      { n: "1136009", name: "Trays, Carryout, 4-Cup Universal With Compartment" },
      { n: "1314080", name: "Rolls, Thermal Paper, 2.25In X 60Ft" },
      { n: "1157836", name: "Knives, White Polypropylene Plastic, Medium Weight, Cutlery" },
      { n: "1163705", name: "Bags, Black Regular Garbage, 35X50In" },
      { n: "1142794", name: "Lids, Clear Plastic Dome, For B Cup, With Hole 12/24oz" },
      { n: "1147228", name: "Containers, 8oz Round Clear Plastic Deli, 8oz, With Clear Lid, Microwaveable" },
      { n: "9302405", name: "Rolls, Thermal Paper, 1Ply, 3 1/8In X 3In, 200Ft" },
      { n: "1413229", name: "Lids, Clear Plastic X-Slot, Recycled PET, For 12-24oz B Cup" },
      { n: "1172791", name: "Lids, Clear Plastic Flat, For 1.5 - 2.5oz Portion Cup" },
      { n: "1341070", name: "Lids, Plastic, For 4-4.5oz Paper Sauce Cup, Ecology Friendly" },
      { n: "1157835", name: "Forks, White Polypropylene Plastic, Medium Weight, Cutlery" },
      { n: "1164661", name: "Napkins, Disposable, Kraft 1Ply X Pressnap" },
    ],
  },
  {
    category: "Special Order",
    items: [
      { n: "1359586", name: "Soft Drink, Dr. Pepper, Pet" },
      { n: "1505049", name: "Sauce, Honey Dill Dipping, Portions" },
      { n: "1351145", name: "Sauce, Roast Garlic Dip, Portioned" },
      { n: "1008343", name: "Bread, Cilantro Garlic Naan, Frozen" },
      { n: "1509657", name: "Bags, Kraft Paper, 12 X 7 X 17In, Custom" },
      { n: "1295451", name: "Ground Wild Boar, 2X5Lb, Frozen" },
      { n: "1282146", name: "Cleaner, Multi Purpose, Perdiem" },
      { n: "1350132", name: "Syrup, Strawberry Sundae, Topping" },
      { n: "1499877", name: "BAG PPR KRAFT CUSTOM 9.75X6X16.75IN" },
      { n: "1455854", name: "Chili Powder, Mexican" },
      { n: "2687605", name: "Smoke, Artificial Liquid" },
      { n: "1497487", name: "Water, Polyethylene, Custom" },
      { n: "1358760", name: "Picks, Bamboo Skewer, 6In, Rifle Design" },
    ],
  },
  {
    category: "Dry Storage",
    items: [
      { n: "1164410", name: "Juice, Lemon" },
      { n: "1249637", name: "Iced Tea, Raspberry, Polyethylene" },
      { n: "1240696", name: "Soft Drink, Rootbeer" },
      { n: "1257292", name: "Drink, Mocha Frappuccino, Glass" },
      { n: "1256572", name: "Energy Drink, Sugar Free Red Bull, Can" },
      { n: "1150639", name: "Seasoning, Chipotle Mango" },
      { n: "1452674", name: "Seasoning Rub, Chipotle Ranch" },
      { n: "1452673", name: "Seasoning Rub, Nashville Hot" },
      { n: "1253445", name: "Seasoning, Maple Bacon" },
      { n: "2950805", name: "Sauce, Thick Teriyaki Glaze, Trans Fat Compliant" },
      { n: "6539856", name: "Sauce, Honey Garlic Wing" },
      { n: "2963005", name: "Sauce, Mesquite Grilling Barbeque, Trans Fat Compliant" },
      { n: "9299605", name: "Rolls, Cash, Paper Printer Visa 3 X 3 2Ply 90Ft" },
      { n: "1217801", name: "Wrap, Film, Roll Clear 11In X 2500Ft Cutter Bo X" },
      { n: "1168644", name: "Wrap, Foil, Regular 18In 45Cm X 100M, Cutter Box" },
      { n: "1223059", name: "Gloves, Large Vinyl, Non Powdered" },
      { n: "1505080", name: "Sauce, Plum, Trans Fat Compliant, Portions" },
      { n: "1225499", name: "Bottles, 16oz Natural Widemouth Squeeze" },
      { n: "1224282", name: "Bottles, 24oz Natural Clear Widemouth Squeeze" },
      { n: "3401217", name: "Salt, Portion" },
      { n: "1070754", name: "Pepper, Spice, Portion" },
      { n: "1077752", name: "Bags, 20Lb Kraft Paper, 8 X 5 X 16In" },
      { n: "1215233", name: "Sports Drink, Fruit Punch Gatorade" },
      { n: "1254182", name: "Gatorade, Cool Blue Raspberry Perform, Pet Bottles" },
      { n: "1366833", name: "Sports Drink, Berry Zero Gatorade, Polyethylene" },
      { n: "1162697", name: "Sports Drink, Grape Gatorade, Polyethylene" },
      { n: "1129378", name: "Mustard, Upside Down Bottle" },
      { n: "1196396", name: "Relish, Sweet, Upside Down Squeeze Bottle" },
      { n: "1188837", name: "Dressing, Creamy Ranch, Gluten Free" },
      { n: "1219312", name: "Onions, Jumbo Yellow, No 2" },
      { n: "1124005", name: "Onions, Jumbo Red, Box" },
      { n: "1211723", name: "Peppers, Chipotle, In Adobo" },
      { n: "6142205", name: "Pepper, Lemon, Seasoning" },
      { n: "1188764", name: "Dressing, Creamy Caesar, Gluten Free" },
      { n: "1393438", name: "Soft Drink, 7Up, Can" },
      { n: "1461568", name: "Seasoning, Shichimi Togarashi" },
      { n: "1069600", name: "Soft Drink, Orange, Crush Can" },
      { n: "8793405", name: "Pepper, Cayenne, Spice, Shaker" },
      { n: "1440606", name: "Powder, Garlic, Spice" },
      { n: "1195906", name: "Soft Drink, Mountain Dew, Can" },
      { n: "1118813", name: "Energy Drink, Red Bull, Can" },
      { n: "1202110", name: "Soft Drink, Ginger Ale, Can" },
      { n: "1317217", name: "Sauce, Tartar" },
      { n: "1108252", name: "Sheets, Paper, Patty 5.25 X 5.25In" },
      { n: "5917805", name: "Flour, Unbleached All Purpose" },
      { n: "9810605", name: "Ketchup, Upside Down Squeeze Bottle" },
      { n: "1141992", name: "Sauce, Honey Mustard" },
      { n: "1441106", name: "Pepper, Ground Black, Spice" },
      { n: "1389230", name: "Soap, Extra Mild Foam Hand" },
      { n: "1188780", name: "Dressing, Creamy Coleslaw, Gluten Free" },
      { n: "1193906", name: "Dressing, Classic Italian" },
      { n: "1294058", name: "Salt, Seasoning" },
      { n: "1223547", name: "Tea, Pure Leaf Lemon, Polyethylene" },
      { n: "1256364", name: "Soft Drink, Pepsi, Can" },
      { n: "1256367", name: "Soft Drink, Diet Pepsi, Can" },
      { n: "1125869", name: "Soft Drink, Root Beer, Mug Can" },
      { n: "1393620", name: "Drink, Iced Tea With Lemon, Cube Pack, Can" },
      { n: "1476536", name: "Sauce, Hot Sriracha" },
      { n: "1253421", name: "Gravy Mix, Poutine, Gluten Free" },
      { n: "1374864", name: "Cleaner, Bleach, 6 Percent" },
      { n: "9547005", name: "Oregano Leaves, Herb" },
      { n: "9546805", name: "Paprika, Spice" },
      { n: "1186303", name: "Pepper, Crushed Red Chili, Spice" },
      { n: "1186315", name: "Onions, Granulated, Spice" },
      { n: "1125457", name: "Oil, Canola, Jib, Zero Trans Fat, Anti Foam" },
      { n: "1351561", name: "Stones, Brick Grill, 4 X 3.5 X 8In" },
      { n: "2418605", name: "Sauce, Original Red Cayenne Pepper Hot" },
      { n: "1163805", name: "Bags, White Regular Garbage, 20X22In" },
      { n: "1140603", name: "Soft Drink, Dr Pepper, Can" },
      { n: "1147698", name: "Salt, Hygrade Fine, #1244" },
      { n: "1116996", name: "Cranberry Sauce, Whole" },
      { n: "1039762", name: "Iced Tea, Iced Brisk, Polyethylene" },
      { n: "5499005", name: "Soft Drink, Diet Pepsi" },
      { n: "1197232", name: "Toilet Tissue, 2 Ply, Miniature Jumbo White 751Ft" },
      { n: "1453902", name: "Batter Mix, Ultimate Fish" },
      { n: "1268709", name: "Tea, Peach, Polyethylene" },
      { n: "2430866", name: "Ketchup, Portion" },
      { n: "2384605", name: "Mustard, 1/4oz Portion" },
      { n: "9552005", name: "Ketchup, Can" },
      { n: "1481216", name: "Syrup, Milkshake Chocolate" },
      { n: "1197237", name: "Towel Rolls, Standard Natural 700Ft" },
      { n: "1254793", name: "Detergent, Sanitizer, Food Surf Quaternary Ammon D10" },
      { n: "1330551", name: "Drink, Original Oat" },
      { n: "5506205", name: "Soft Drink, Pepsi" },
      { n: "9280805", name: "Topping, Platescapers Caramel Coulis" },
      { n: "1424659", name: "Spray, Nonstick Pan, Light Canola Oil" },
      { n: "8874205", name: "Liners, 12 X 12In Black And White Checkered Basket" },
      { n: "8797405", name: "Dill Weed, Spice, Herb, Shaker, Trans Fat Compliant" },
      { n: "6991005", name: "Bags, 3Lb Clear Polyethylene, 5 X 2 X 11.5In" },
      { n: "5933605", name: "Mix, Classic Buttermilk Pancake, Bag" },
      { n: "7159205", name: "Croutons, 3/4In Diced Homestyle Garlic" },
      { n: "9644005", name: "Vinegar, Pure Distilled White" },
      { n: "1087483", name: "Mayonnaise, Real" },
    ],
  },
  {
    category: "Freezer",
    items: [
      { n: "1059292", name: "Cod Fillets, Blue, 4oz, Marine Stewardship Council, Individually Quick Frozen" },
      { n: "6060605", name: "Lamb, Ground, Frozen" },
      { n: "1140919", name: "Bison, Ground, Frozen" },
      { n: "1258022", name: "Elk, Ground, Frozen" },
      { n: "1087521", name: "Guacamole, Pouch California Supreme, Frozen" },
      { n: "1515063", name: "Cod Fillets, 3oz Regular Blue, Chemical Free, Marine Stewardship Council, Frozen, Obuy" },
      { n: "1337614", name: "Pineapple Chunks, Individual Quick Frozen" },
      { n: "1321571", name: "Pickle Spears, Breaded Spear Dill, Frozen Appetizer" },
      { n: "1261474", name: "Buns, 5In Burger, Gluten Free, Thaw & Serve, Individually Wrapped Portions" },
      { n: "1367000", name: "Cauliflower, Tempura Battered" },
      { n: "1402585", name: "Buns, 4In Sesame Hamburger" },
      { n: "1190000", name: "Turkey, Extra Lean Ground, White And Dark Meat, Frozen" },
      { n: "1201995", name: "Burger Patties, Malibu Gardenburger Veggie, Frozen" },
      { n: "1287402", name: "Chicken Breast, Fillets/Tender, Raw, Bulk, Frozen" },
      { n: "1505362", name: "Tortilla Wraps, 12In Salsa Flavor Flour, Frozen" },
      { n: "1278126", name: "Buns, 4In Sliced Brioche Hamburger, Thaw & Serve" },
      { n: "1501783", name: "Rolls, 4In Potato" },
      { n: "1165166", name: "Ice Cream, Vanilla" },
      { n: "1203451", name: "Sweet Potato Fries, Thin Cut Oven Ready, 5/16In" },
      { n: "1317050", name: "Fries, Clear Coat Short Cut, 3/8In" },
      { n: "1240254", name: "Chicken Wings, Roasted Roadhouse Seasoned, Cooked, Frozen" },
      { n: "1474335", name: "Chicken Breast, 5oz Boneless Skinless, 17 Percent, Individually Quick Frozen" },
      { n: "1337634", name: "Bananas, Sliced, Frozen" },
      { n: "1477007", name: "Strawberries, Whole, Individually Quick Frozen" },
      { n: "1491861", name: "Brownies, Fudge, Gluten Free, Frozen" },
      { n: "1477004", name: "Mango Chunks, Individually Quick Frozen" },
      { n: "1131533", name: "Frozen Yogurt, Vanilla, Good For You" },
      { n: "1252456", name: "Buns, 4.25In Gourmet Pretzel, Vegetarian, Thaw And Serve" },
      { n: "2856805", name: "Berries, 4 Fruit Burst, Individually Quick Frozen" },
      { n: "1363117", name: "Pork Ribs, Breaded Boneless, Fully Cooked, Frozen" },
      { n: "1445476", name: "Onion Rings, Gourmet Panko Breaded, 3/8, Appetizer" },
      { n: "1363204", name: "Cheese Curd, 29 Percent, Individually Quick Frozen" },
      { n: "1228605", name: "Cheese Sticks, Battered Mozzarella, Frozen, Appetizer" },
    ],
  },
  {
    category: "Cooler",
    items: [
      { n: "1311589", name: "Peppers, Choice Green, 20-25 Pounds, Volume Filled" },
      { n: "1568005", name: "Lettuce, Premium Green Leaf" },
      { n: "1275005", name: "Cilantro, Washed & Trimmed, Herb Fresh" },
      { n: "9821205", name: "Pickles, 3/16In Long Sliced Sandwich Strip Dill, 775-885 Count, Fresh" },
      { n: "1345202", name: "Cheese, Shaved Asiago Parmesan Romano" },
      { n: "1486659", name: "Beef Burgers, 3oz Chuck, Fresh" },
      { n: "1486658", name: "Beef Burgers, 5oz Chuck, Fresh" },
      { n: "1326088", name: "Mushrooms, Premium Medium, #1" },
      { n: "1445202", name: "Cheese, Sliced Natural Mild Cheddar, 21G, Col" },
      { n: "1444888", name: "Cheese, Sliced Natural Swiss, 14G" },
      { n: "1209607", name: "Tomatoes, Greenhouse Beefsteak, 28-35Ct Hh, Chain" },
      { n: "1282605", name: "Parsley, Washed Trimmed Cello, Herb" },
      { n: "1279823", name: "Lettuce, Romaine Hearts" },
      { n: "1060304", name: "Whipped Cream, Real, Aerosol" },
      { n: "7002005", name: "Buttermilk, 3.25 Percent" },
      { n: "1445199", name: "Cheese, Sliced Natural Mozzarella, 21G" },
      { n: "1635405", name: "Carrots, Jumbo" },
      { n: "1201153", name: "Cabbage, Green" },
      { n: "1055452", name: "Spread, Garlic, Zero Trans Fat" },
      { n: "5391205", name: "Bacon, Center Cut, +/-1 Slice, 14 Slices per 2In, Raw, Fresh" },
      { n: "6840156", name: "Cheese, Coloured Shredded Mild Cheddar" },
      { n: "2171605", name: "Garlic, Minced, Not In Oil Trans Fat Compliant" },
      { n: "1424145", name: "Mint, Fresh" },
    ],
  },
  {
    category: "Saputo / Family Pizza",
    items: [
      { n: "51547", name: "SAPUTO 20% Pizza Mozzarella IQF 2x5kg" },
      { n: "487250", name: "ARMSTRONG Yellow Mild Cheddar Shred 4x2.5 Kg" },
      { n: "487264", name: "SAPUTO Light Parmesan Angel Hair Shred 2x1kg" },
      { n: "50585", name: "VITALITE Dairy-Free Mozzarella Flavoured Shred 3x2 Kg" },
      { n: "87394", name: "NSK SMOKED SL HAM 75MM 10x1KG" },
      { n: "87207", name: "BLV Smoked Salami Sliced 10x1 Kg" },
      { n: "52916", name: "BLV Smoked Pepperoni Sliced 10x1 Kg" },
      { n: "89686", name: "MTT 2KG F/C BONLESS GARLC RIB*2 ( For Deepfryer )" },
      { n: "87848", name: "SOF Breaded CHICKEN WINGS F/C 2x2KG ( For Deepfryer )" },
      { n: "52090", name: "BLV Cooked Italian Sausage crumbles 2.27 Kg" },
      { n: "87734", name: "MLF F/C SHAVED STEAK 4x1.36KG" },
      { n: "75481", name: "FPZ SPICE BEEF TOPPING 2x2.5KG" },
      { n: "52259", name: "CHERRY PINK CPK HOT ITALIAN SAUS SL 2x2.5K" },
      { n: "89434", name: "MCC 5LBS BATTERED MUSHROOMS *1" },
      { n: "78257", name: "CVD SEASONED WEDGES 6x5LBS" },
      { n: "75095", name: "FAMILY FAM PIZZA SAUCE-BAG 6x3L" },
      { n: "74050", name: "FAMILY PIZZA 20KG ALL PURPOSE FLOUR *1" },
      { n: "88407", name: "LESAFFRE LES 454G INSTANT YEAST *20" },
      { n: "78799", name: "RICH'S RCS G/F PZZ CRST 10\"CAULIFLOWR" },
      { n: "3002", name: "BELVARIO Mafalda Pasta 4.54 Kg" },
      { n: "3008", name: "BELVARIO Fettuccini Pasta 9.07 Kg" },
      { n: "3004", name: "BELVARIO Penne Rigate Pasta 9.07 Kg" },
      { n: "78019", name: "BELVARIO Hot Pepper Rings 3.78 L" },
      { n: "89630", name: "BLV 2.84L JAL PEPPER SL PCKL*6" },
      { n: "3320", name: "BELVARIO Pizza-Cut Pineapple 2.84 L" },
      { n: "3419", name: "BELVARIO Sliced Black Olives 2.84 L" },
      { n: "78717", name: "HELLMANN'S HLM CHEESY JALAPE CUP 108x44ML" },
      { n: "78716", name: "HELLMANN'S HLM ROASTD GARLIC DIP 108x44ML" },
      { n: "78746", name: "HELLMANN'S HLM ANCHO CHIPOTLE DIP108x44ML" },
      { n: "78737", name: "HELLMANN'S HLM RANCH SAUCE DIP 108x44ML" },
      { n: "165340", name: "DAIRYLAND 14% Sour Cream 4 L" },
      { n: "77574", name: "OLD STYLE OST HONEY DILL SAUCE 2x4L" },
      { n: "88993", name: "SMUCKER'S SMU 1.89L BAJA CHIPOTLE SCE *2" },
      { n: "78492", name: "HELLMANN'S HLM ANCHO CHIPOTL SCE 2x3.78L" },
      { n: "78872", name: "FAMILY PIZZA FPZ W/B PIZZA BOX 8\" 50/BDL" },
      { n: "74473", name: "FAMILY PIZZA FPZ W/B PIZZA BOX 10\" 50/BDL" },
      { n: "78868", name: "FAMILY PIZZA FPZ W/B PIZZA BOX 12\" 50/BDL" },
      { n: "74475", name: "FAMILY PIZZA FPZ W/B BOX PIZZA 15\" 50/BDL" },
      { n: "9105", name: "DAWN FOODS DWF WHT ICING POUCH 12x907G" },
      { n: "89640", name: "DWF 945G APPLE SPICE FILLI*12" },
      { n: "89257", name: "TABLE ACCENT TAC PIZZA BOX SUPPORT 1000/CS" },
      { n: "3219", name: "FULL RED FUR PREP PIZZA SAUCE100oz 6/CS (gluten free)" },
    ],
  },
  {
    category: "Sysco",
    items: [
      { n: "", name: "Chicken" },
      { n: "", name: "Bacon Crumbled" },
      { n: "", name: "Alfredo" },
      { n: "", name: "Yellow Onions" },
      { n: "", name: "Sweet & Sour portions" },
      { n: "", name: "honey mustard portions" },
      { n: "", name: "Grill Brick" },
      { n: "", name: "tartar portions" },
    ],
  },
  {
    category: "Local",
    items: [
      { n: "", name: "Sour Cream" },
      { n: "", name: "cinnamon powder" },
      { n: "", name: "greek seasoning" },
      { n: "", name: "butter" },
      { n: "", name: "cracked black pepper" },
      { n: "", name: "Cucumber" },
      { n: "", name: "Red Bell Pepper" },
      { n: "", name: "Lemon" },
      { n: "", name: "Beer" },
      { n: "", name: "Bleach" },
      { n: "", name: "Milk" },
      { n: "", name: "Eggs" },
      { n: "", name: "Ginger Paste" },
      { n: "", name: "Cumin powder" },
      { n: "", name: "Corriander powder" },
      { n: "", name: "Aloo Tikki" },
      { n: "", name: "Coffee" },
      { n: "", name: "Oreo Cookies" },
      { n: "", name: "Scrubber or steel wool" },
      { n: "", name: "Biscoff paste" },
      { n: "", name: "Vegan Mayo" },
      { n: "", name: "Brown Sugar" },
      { n: "", name: "Mustard Powder" },
      { n: "", name: "Turmeric Powder" },
    ],
  },
];

/** Total distinct catalog items across all categories (253). */
export const ORDER_GUIDE_ITEM_COUNT = BROOKS_ORDER_GUIDE.reduce(
  (sum, c) => sum + c.items.length,
  0,
);
