export interface Recipe {
  id: number;
  name: string;
  yield: string;
  ingredients: { item: string; amount: string }[];
  method: string[];
}

export const recipes: Recipe[] = [
  {
    id: 1,
    name: "Avocado Sauce",
    yield: "",
    ingredients: [
      { item: "Sour Cream", amount: "2 cups" },
      { item: "Mayonnaise", amount: "1 cup" },
      { item: "White Sugar", amount: "1 tbsp" },
      { item: "Dry Dill", amount: "¼ tbsp" },
      { item: "Turmeric", amount: "½ tsp" },
      { item: "Mustard Powder", amount: "½ tsp" },
      { item: "Guacamole", amount: "½ bag" },
      { item: "Lemon Juice", amount: "½ tbsp" },
      { item: "Apple Cider Vinegar", amount: "60 ml" },
    ],
    method: [
      "Add all ingredients into a mixing bowl.",
      "Use a hand blender to blend until smooth and creamy in texture.",
      "Transfer the sauce into a Cambro container.",
      "Label and refrigerate until ready to use.",
    ],
  },
  {
    id: 2,
    name: "Bacon Ketchup",
    yield: "1.25 Litres",
    ingredients: [
      { item: "Ketchup", amount: "1 litre" },
      { item: "Bacon Grease", amount: "250 ml" },
    ],
    method: [
      "Pour both ingredients into a mixing bowl.",
      "Mix thoroughly until fully combined and smooth.",
      "Transfer the mixture into a Cambro container.",
      "Label and refrigerate until ready to use.",
    ],
  },
  {
    id: 3,
    name: "Bison Patty",
    yield: "17 counts",
    ingredients: [
      { item: "Minced Bison Meat", amount: "1 pack (2.5 kg)" },
      { item: "Egg", amount: "1" },
    ],
    method: [
      "Combine the minced bison meat and egg in a dough mixer.",
      "Mix thoroughly until the mixture is well combined and evenly blended.",
      "Portion 5 oz of the mixture and shape into a ball.",
      "Place the meat ball in a patty press and flatten to form a patty.",
      "Place a patty paper (lightly sprayed with pan spray) between each patty.",
      "Stack the patties neatly in a container.",
      "Label the container and refrigerate until ready to use.",
    ],
  },
  {
    id: 4,
    name: "Boar Patty",
    yield: "19 counts",
    ingredients: [
      { item: "Minced Boar Meat", amount: "1 pack (2.5 kg)" },
      { item: "Egg", amount: "1" },
    ],
    method: [
      "Combine the minced boar meat and egg in a dough mixer.",
      "Mix thoroughly until the mixture is well combined and smooth.",
      "Portion 4.5 oz of the mixed boar meat and shape it into a ball.",
      "Place the meat ball in a patty press and flatten it to form a patty.",
      "Place a patty paper (lightly sprayed with pan spray) between each patty.",
      "Stack the patties neatly in a container.",
      "Label and refrigerate until ready to use.",
    ],
  },
  {
    id: 5,
    name: "Breading",
    yield: "",
    ingredients: [
      { item: "Flour", amount: "12.5 lbs" },
      { item: "Salt", amount: "0.75 cup" },
      { item: "Ground Black Pepper", amount: "0.75 cup" },
      { item: "Paprika", amount: "0.25 cup" },
      { item: "Garlic Powder", amount: "0.5 cup" },
      { item: "Onion Powder", amount: "0.5 cup" },
      { item: "Cayenne Pepper", amount: "2 tbsp" },
    ],
    method: [
      "Wear gloves before handling ingredients.",
      "Add all ingredients into a bus bin or large mixing container.",
      "Mix thoroughly by hand until fully combined.",
      "Label the container clearly for storage and use.",
    ],
  },
  {
    id: 6,
    name: "Buffalo Sauce",
    yield: "2 Litres",
    ingredients: [
      { item: "Ranch Dressing", amount: "1 litre" },
      { item: "Frank's RedHot Sauce", amount: "1 litre" },
    ],
    method: [
      "Transfer Ranch and Frank's RedHot Sauce into a mixing bowl.",
      "Mix thoroughly until fully combined.",
      "Transfer the sauce into a Cambro container.",
      "Label and refrigerate until ready to use.",
    ],
  },
  {
    id: 7,
    name: "Cajun Spice",
    yield: "1.75 Litres",
    ingredients: [
      { item: "Mexican Chili Powder", amount: "16 fl.oz" },
      { item: "Paprika", amount: "16 fl.oz" },
      { item: "Brown Sugar", amount: "12 fl.oz" },
      { item: "Ground Black Pepper", amount: "4 fl.oz" },
      { item: "Garlic Powder", amount: "8 fl.oz" },
      { item: "Cumin Powder", amount: "4 fl.oz" },
    ],
    method: [
      "Wear gloves before handling the spices.",
      "Add all ingredients into a mixing container.",
      "Mix thoroughly until fully combined.",
      "Transfer the spice mix into a storage container.",
      "Label clearly for future use.",
    ],
  },
  {
    id: 8,
    name: "Chipotle Mayo",
    yield: "1 litre",
    ingredients: [
      { item: "Mayonnaise", amount: "1 L" },
      { item: "Cilantro", amount: "1 oz" },
      { item: "Lemon Juice", amount: "1 tbsp" },
      { item: "Chipotle Paste", amount: "1 tbsp" },
    ],
    method: [
      "Roughly chop the cilantro.",
      "Combine all ingredients in a mixing bowl.",
      "Mix thoroughly until smooth and well blended.",
      "Transfer the mixture into a Cambro container.",
      "Label and refrigerate until ready to use.",
    ],
  },
  {
    id: 9,
    name: "Chipotle Mint",
    yield: "1 Litre",
    ingredients: [
      { item: "Chipotle Mayo", amount: "1 litre" },
      { item: "Mint Chutney", amount: "6 tbsp" },
    ],
    method: [
      "Transfer Chipotle Mayo and Mint Chutney into a mixing bowl.",
      "Mix thoroughly until fully combined and smooth.",
      "Transfer the mixture into a Cambro container.",
      "Label and refrigerate until ready to use.",
    ],
  },
  {
    id: 10,
    name: "Chipotle Paste",
    yield: "8 fl.oz",
    ingredients: [
      { item: "Chipotle Peppers", amount: "1 can" },
      { item: "Canola Oil", amount: "2 fl.oz" },
      { item: "Water", amount: "1 fl.oz" },
    ],
    method: [
      "Combine chipotle peppers, canola oil, and water in a mixing bowl.",
      "Use an immersion blender to blend the mixture into a smooth paste.",
      "Transfer the paste into a food insert.",
      "Label and refrigerate until ready to use.",
    ],
  },
  {
    id: 11,
    name: "Coleslaw Mix",
    yield: "2.5 Litres",
    ingredients: [
      { item: "Cabbage", amount: "750 g" },
      { item: "Whole Carrots", amount: "140 g" },
      { item: "Onion Slivers", amount: "140 g" },
      { item: "Parsley", amount: "30 g" },
    ],
    method: [
      "Shred the cabbage using a mandolin slicer and transfer it into a mixing bowl.",
      "Grate the whole carrots to create carrot matchsticks and add them to the bowl.",
      "Thinly slice the red onions and finely chop the parsley; add them to the bowl.",
      "Mix all ingredients thoroughly by hand until evenly combined.",
      "Transfer the coleslaw into a Cambro container.",
      "Label and refrigerate until ready to use.",
    ],
  },
  {
    id: 12,
    name: "Elk Patty",
    yield: "19 Counts",
    ingredients: [
      { item: "Minced Elk Meat", amount: "1 pack (2.25 kg)" },
      { item: "Garlic Butter", amount: "1 cup" },
      { item: "Chopped Parsley", amount: "2 fl.oz" },
      { item: "Black Pepper", amount: "2 tsp" },
      { item: "Salt", amount: "2 tsp" },
      { item: "Paprika", amount: "2 tsp" },
      { item: "Cayenne Pepper", amount: "1 tsp" },
      { item: "Minced Garlic", amount: "2 tbsp" },
    ],
    method: [
      "Combine all ingredients in a dough mixer and mix thoroughly until fully blended.",
      "Portion 4.5 oz of the mixture and shape into a ball.",
      "Place the meat ball in a patty press and flatten to form a patty.",
      "Place a patty paper (lightly sprayed with pan spray) between each patty.",
      "Stack the patties neatly in a container.",
      "Label and refrigerate until ready to use.",
    ],
  },
  {
    id: 13,
    name: "Fish Batter Mix",
    yield: "855 ml",
    ingredients: [
      { item: "Fish Breading Mix", amount: "9.5 oz" },
      { item: "Beer", amount: "355 ml (1 can)" },
    ],
    method: [
      "Combine fish breading mix and beer in a mixing bowl.",
      "Whisk thoroughly until smooth and lump-free.",
      "Transfer the mixture into a Cambro container.",
      "Label and refrigerate until ready to use.",
    ],
  },
  {
    id: 14,
    name: "Greek Dressing",
    yield: "1.75L",
    ingredients: [
      { item: "Italian Jug Dressing", amount: "1 litre" },
      { item: "Ranch Dressing", amount: "600 ml" },
      { item: "Bottled Lemon Juice", amount: "120 ml" },
      { item: "Minced Garlic", amount: "2 tbsp" },
      { item: "Canola Oil", amount: "375 ml" },
      { item: "White Vinegar", amount: "50 ml" },
      { item: "Dry Oregano", amount: "2 tbsp" },
    ],
    method: [
      "Combine all ingredients except canola oil in a mixing bowl.",
      "Slowly emulsify the oil from the top into the mixture, ensuring the dressing becomes smooth and well combined.",
      "Transfer the dressing into a container.",
      "Label and refrigerate until ready to use.",
    ],
  },
  {
    id: 15,
    name: "Herbed Mayo",
    yield: "1.75 L",
    ingredients: [
      { item: "Mayonnaise", amount: "1.75 L" },
      { item: "Chopped Cilantro", amount: "1 cup" },
      { item: "Black Pepper", amount: "1 tbsp" },
      { item: "Salt", amount: "0.5 tbsp" },
      { item: "Minced Garlic", amount: "2 tbsp" },
      { item: "Lemon Zest", amount: "1 tbsp" },
      { item: "Lemon Juice", amount: "50 ml" },
    ],
    method: [
      "Combine all ingredients in a stainless-steel mixing bowl.",
      "Mix thoroughly until smooth and well blended.",
      "Transfer the mixture into a Cambro container.",
      "Cover with lid, label, and refrigerate until ready to use.",
    ],
  },
  {
    id: 16,
    name: "Lamb Patty",
    yield: "19 Counts",
    ingredients: [
      { item: "Minced Lamb Meat", amount: "2.5 kg" },
      { item: "Garlic Butter", amount: "6.25 tbsp" },
      { item: "Coriander Powder", amount: "2.5 tsp" },
      { item: "Cumin Powder", amount: "2.5 tsp" },
      { item: "Paprika", amount: "2.5 tsp" },
      { item: "Salt", amount: "2.5 tsp" },
      { item: "Black Pepper", amount: "2.5 tsp" },
      { item: "Minced Ginger", amount: "2.5 tsp" },
      { item: "Minced Garlic", amount: "2.5 tbsp" },
      { item: "Chopped Red Onions", amount: "10 fl.oz" },
      { item: "Chilli Flakes", amount: "1.25 tsp" },
      { item: "Eggs", amount: "1 no." },
    ],
    method: [
      "Combine all ingredients in a dough mixer and mix thoroughly until fully blended.",
      "Portion 4.5 oz of the mixture and shape into balls.",
      "Place the meat balls in a patty press and flatten to form patties.",
      "Place a patty paper (lightly sprayed with pan spray) between each patty.",
      "Stack the patties neatly in a container.",
      "Label and refrigerate until ready to use.",
    ],
  },
  {
    id: 17,
    name: "Mint Chutney",
    yield: "500 ml",
    ingredients: [
      { item: "Mint Leaves", amount: "3 cups (tightly packed)" },
      { item: "Cilantro Leaves", amount: "4 cups (tightly packed)" },
      { item: "Minced Garlic", amount: "6 tbsp" },
      { item: "Minced Ginger", amount: "2 tbsp" },
      { item: "Lemon Juice", amount: "4 tbsp" },
      { item: "Cumin Powder", amount: "1 tbsp" },
      { item: "Salt", amount: "2 tsp" },
      { item: "Sugar", amount: "1.5 tsp" },
      { item: "Water", amount: "150 ml" },
      { item: "Onion (medium)", amount: "roughly chopped" },
    ],
    method: [
      "Rinse the mint and cilantro leaves thoroughly under running water.",
      "Add all ingredients—mint, cilantro, garlic, ginger, onion, lemon juice, cumin powder, salt, sugar, and water—into a blender.",
      "Blend until smooth, scraping down the sides as needed to ensure even mixing.",
      "Transfer the chutney into an airtight container.",
      "Label and refrigerate. Use within 5–6 days.",
    ],
  },
  {
    id: 18,
    name: "Oreo Batter Mix",
    yield: "800 ml",
    ingredients: [
      { item: "Pancake Mix", amount: "500 ml (2 cups)" },
      { item: "Egg", amount: "1" },
      { item: "Milk", amount: "300 ml" },
    ],
    method: [
      "Combine pancake mix, egg, and milk in a mixing bowl.",
      "Whisk thoroughly until smooth and lump-free.",
      "Transfer the batter into a Cambro container.",
      "Label and refrigerate until ready to use.",
    ],
  },
  {
    id: 19,
    name: "Smoky Mayo",
    yield: "1 Litre",
    ingredients: [
      { item: "Mayonnaise", amount: "1 litre" },
      { item: "Liquid Smoky Flavour", amount: "2 tbsp" },
    ],
    method: [
      "Combine mayonnaise and liquid smoky flavour in a mixing bowl.",
      "Mix thoroughly until smooth and fully combined.",
      "Transfer the mixture into a Cambro container.",
      "Label and refrigerate until ready to use.",
    ],
  },
  {
    id: 20,
    name: "Spicy Cranberry",
    yield: "500 ml",
    ingredients: [
      { item: "Cranberry Jelly Sauce", amount: "348 ml (can)" },
      { item: "Sriracha", amount: "9 fl.oz" },
    ],
    method: [
      "Transfer cranberry jelly sauce and Sriracha into a mixing bowl.",
      "Mix thoroughly until well combined and smooth.",
      "Transfer the sauce into a Cambro container.",
      "Label and refrigerate until ready to use.",
    ],
  },
  {
    id: 21,
    name: "Sriracha Mayo",
    yield: "1.25 Litres",
    ingredients: [
      { item: "Mayonnaise", amount: "1 litre" },
      { item: "Sriracha", amount: "8 fl.oz" },
      { item: "Lime Juice", amount: "1 tbsp" },
      { item: "Togarashi", amount: "1 tbsp" },
    ],
    method: [
      "Combine all ingredients in a mixing bowl.",
      "Mix thoroughly until smooth and fully combined.",
      "Transfer the mixture into a Cambro container.",
      "Label and refrigerate until ready to use.",
    ],
  },
];
